CONTIKI = ../..

all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors multihop1 multihop2\
     multihop_sink multihop_forward multihop_source


include $(CONTIKI)/Makefile.include
